### ISSUE TITLE
Getters should accept empty results for optional properties

### ISSUE THREAD

**Issue by krokodok** [tollwerk/vamoso-soap#3]
If not known which fields are optional maybe just all. In my current case it's the property `External Station ID` of StationType. But I suppose there'll be more occasions where we'll have this problem.

**Comment by krokodok** [comment]
Now I also have the problem with property `Coordinates`.

**Comment by jkphl** [comment]
This one's a difficult one as

* there's no reliable source of which properties are really optional and
* walking through all the models seems a too arduous so we should fix this on demand only.

At least the `Station` model should be corrected now, however
